services:
  guri-chan:
    build: .
    image: guri-chan:latest
    container_name: guri-chan
    ports:
      - "5001:5001"
    volumes:
      - "./app:/app"
    environment:
      APP_PORT: 5001
      CHANNEL_ACCESS_TOKEN: "${CHANNEL_ACCESS_TOKEN}"
      CHANNEL_SECRET: "${CHANNEL_SECRET}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      UPLOAD_SIGNATURE: "${UPLOAD_SIGNATURE}"
      CLOUDFRONT_URL: "${CLOUDFRONT_URL}"      

